sudo: required
services: 
  - docker

before_install:
  - docker build -t rogerrogeryau/docker-react -f Dockerfile.dev .

script:
  - docker run rogerrogeryau/docker-react npm run ci_test -- --coverage
  

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-198353370668"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_ACCESS_KEY"


