sudo: required
services: 
  - docker

before_install:
  - docker build -t rogerrogeryau/docker-react -f Dockerfile.dev .

script:
  - docker run rogerrogeryau/docker-react npm run test -- --coverage

