FROM node:alpine

WORKDIR '/app'

COPY package.json .  

RUN npm install

COPY . .            

CMD ["npm", "run", "start"]  

#docker run -f 3000:3000 1b388c7304a8    #port mapping needed